import { supabase } from '@/lib/supabase/client';
import {
  Section,
  Member,
  Announcement,
  Assignment,
  Task,
  Note,
  Event,
  Resource,
  EntityType,
} from '@/types/database';
import { ImportItem } from '@/types/importSchema';
import { SectionRepository } from './adapter';
import { transformImportItemToEntity } from '../validation/jsonValidator';

/**
 * Supabase-backed SectionRepository (Phase 2).
 *
 * - Reads work for anyone (public read policies, no login).
 * - Writes only succeed for a session that was promoted to admin by the
 *   `verify-admin-access` Edge Function. Row Level Security enforces that on the
 *   server, so a blocked write surfaces here as a clear error.
 * - IDs and created_at / updated_at are generated by Postgres.
 */

const SECTION_CODE = 'BSIT 1-1';
const POLL_INTERVAL_MS = 60_000;
const LEGACY_LOCAL_KEYS = ['section_lobby_bsit11_v1', 'section_lobby_data_v1'];

type ContentTable =
  | 'announcements'
  | 'assignments'
  | 'tasks'
  | 'notes'
  | 'events'
  | 'resources';
type Table = ContentTable | 'members' | 'sections';

const TABLE_BY_TYPE: Record<EntityType, ContentTable> = {
  announcement: 'announcements',
  assignment: 'assignments',
  task: 'tasks',
  note: 'notes',
  event: 'events',
  resource: 'resources',
};

const PERMISSION_HINT =
  'Not found, or you do not have permission. Enter the administrator access code again if your session expired.';

function fail(context: string, error: { message: string }): never {
  throw new Error(`${context}: ${error.message}`);
}

/** Never send server-managed columns back in an update. */
function cleanUpdates(updates: object): Record<string, unknown> {
  const { id: _id, created_at: _created, updated_at: _updated, ...rest } = updates as Record<string, unknown>;
  return rest;
}

const byDateAsc = (a: string, b: string) => new Date(a).getTime() - new Date(b).getTime();
const byDateDesc = (a: string, b: string) => new Date(b).getTime() - new Date(a).getTime();

class SupabaseSectionStore implements SectionRepository {
  private listeners = new Set<() => void>();
  private pollTimer: ReturnType<typeof setInterval> | null = null;

  // ---------- internals ----------

  private notify() {
    this.listeners.forEach((listener) => {
      try {
        listener();
      } catch (err) {
        console.error('Error executing store listener:', err);
      }
    });
  }

  private async list<T>(table: Table, build?: (query: any) => any): Promise<T[]> {
    const base: any = supabase.from(table).select('*');
    const { data, error } = await (build ? build(base) : base);
    if (error) fail(`Failed to load ${table}`, error);
    return (data ?? []) as T[];
  }

  private async insertOne<T>(table: Table, row: object): Promise<T> {
    const { data, error } = await supabase.from(table).insert(row).select().single();
    if (error) fail(`Failed to create ${table} record`, error);
    this.notify();
    return data as T;
  }

  private async updateOne<T>(table: Table, id: string, updates: object, touchUpdatedAt: boolean): Promise<T> {
    const payload = {
      ...cleanUpdates(updates),
      ...(touchUpdatedAt ? { updated_at: new Date().toISOString() } : {}),
    };
    const { data, error } = await supabase.from(table).update(payload).eq('id', id).select().maybeSingle();
    if (error) fail(`Failed to update ${table} record`, error);
    if (!data) throw new Error(`Failed to update ${table} record: ${PERMISSION_HINT}`);
    this.notify();
    return data as T;
  }

  private async deleteOne(table: Table, id: string): Promise<void> {
    const { data, error } = await supabase.from(table).delete().eq('id', id).select('id');
    if (error) fail(`Failed to delete ${table} record`, error);
    if (!data || data.length === 0) throw new Error(`Failed to delete ${table} record: ${PERMISSION_HINT}`);
    this.notify();
  }

  // ---------- subscribe / refresh ----------

  private onVisible = () => {
    if (typeof document !== 'undefined' && document.visibilityState === 'visible') this.notify();
  };

  private startPolling() {
    if (typeof window === 'undefined') return;
    this.pollTimer = setInterval(this.onVisible, POLL_INTERVAL_MS);
    document.addEventListener('visibilitychange', this.onVisible);
    window.addEventListener('focus', this.onVisible);
  }

  private stopPolling() {
    if (this.pollTimer) clearInterval(this.pollTimer);
    this.pollTimer = null;
    if (typeof window === 'undefined') return;
    document.removeEventListener('visibilitychange', this.onVisible);
    window.removeEventListener('focus', this.onVisible);
  }

  /**
   * Own writes notify immediately. Changes from other devices arrive when the
   * tab regains focus or on the 60s poll while visible.
   */
  public subscribe(callback: () => void): () => void {
    this.listeners.add(callback);
    if (this.listeners.size === 1) this.startPolling();
    return () => {
      this.listeners.delete(callback);
      if (this.listeners.size === 0) this.stopPolling();
    };
  }

  /**
   * The shared database is never wiped from the client. This only drops the
   * old browser-only cache from Phase 1 and reloads from Supabase.
   */
  public async resetToDefault(): Promise<void> {
    try {
      LEGACY_LOCAL_KEYS.forEach((key) => window.localStorage.removeItem(key));
    } catch {
      /* storage unavailable: nothing to clear */
    }
    this.notify();
  }

  // ---------- section ----------

  public async getSection(): Promise<Section> {
    const { data, error } = await supabase.from('sections').select('*').eq('code', SECTION_CODE).maybeSingle();
    if (error) fail('Failed to load section', error);
    if (!data) {
      throw new Error(
        `Section "${SECTION_CODE}" could not be read. Check that it exists and that the public read policies migration is applied.`,
      );
    }
    return data as Section;
  }

  public async updateSection(section: Partial<Section>): Promise<Section> {
    const current = await this.getSection();
    return this.updateOne<Section>('sections', current.id, section, true);
  }

  // ---------- announcements ----------

  public async getAnnouncements(includeArchived = false): Promise<Announcement[]> {
    const rows = await this.list<Announcement>('announcements', (q) =>
      includeArchived ? q : q.neq('status', 'archived'),
    );
    return rows.sort((a, b) => byDateDesc(a.published_at, b.published_at));
  }

  public createAnnouncement(item: Omit<Announcement, 'id' | 'created_at' | 'updated_at'>) {
    return this.insertOne<Announcement>('announcements', item);
  }

  public updateAnnouncement(id: string, updates: Partial<Announcement>) {
    return this.updateOne<Announcement>('announcements', id, updates, true);
  }

  public async archiveAnnouncement(id: string) {
    await this.updateAnnouncement(id, { status: 'archived' });
  }

  public deleteAnnouncement(id: string) {
    return this.deleteOne('announcements', id);
  }

  // ---------- assignments ----------

  public async getAssignments(includeArchived = false): Promise<Assignment[]> {
    const rows = await this.list<Assignment>('assignments', (q) =>
      includeArchived ? q : q.neq('status', 'archived'),
    );
    return rows.sort((a, b) => byDateAsc(a.due_at, b.due_at));
  }

  public createAssignment(item: Omit<Assignment, 'id' | 'created_at' | 'updated_at'>) {
    return this.insertOne<Assignment>('assignments', item);
  }

  public updateAssignment(id: string, updates: Partial<Assignment>) {
    return this.updateOne<Assignment>('assignments', id, updates, true);
  }

  public async archiveAssignment(id: string) {
    await this.updateAssignment(id, { status: 'archived' });
  }

  public deleteAssignment(id: string) {
    return this.deleteOne('assignments', id);
  }

  // ---------- tasks ----------

  public async getTasks(includeArchived = false): Promise<Task[]> {
    const rows = await this.list<Task>('tasks', (q) => (includeArchived ? q : q.neq('status', 'archived')));
    return rows.sort((a, b) => {
      if (a.due_at && b.due_at) return byDateAsc(a.due_at, b.due_at);
      if (a.due_at) return -1;
      if (b.due_at) return 1;
      return byDateDesc(a.created_at, b.created_at);
    });
  }

  public createTask(item: Omit<Task, 'id' | 'created_at' | 'updated_at'>) {
    return this.insertOne<Task>('tasks', item);
  }

  public updateTask(id: string, updates: Partial<Task>) {
    return this.updateOne<Task>('tasks', id, updates, true);
  }

  public async archiveTask(id: string) {
    await this.updateTask(id, { status: 'archived' });
  }

  public deleteTask(id: string) {
    return this.deleteOne('tasks', id);
  }

  // ---------- notes ----------

  public async getNotes(includeArchived = false): Promise<Note[]> {
    const rows = await this.list<Note>('notes', (q) => (includeArchived ? q : q.neq('status', 'archived')));
    return rows.sort((a, b) => byDateDesc(a.created_at, b.created_at));
  }

  public createNote(item: Omit<Note, 'id' | 'created_at' | 'updated_at'>) {
    return this.insertOne<Note>('notes', item);
  }

  public updateNote(id: string, updates: Partial<Note>) {
    return this.updateOne<Note>('notes', id, updates, true);
  }

  public async archiveNote(id: string) {
    await this.updateNote(id, { status: 'archived' });
  }

  public deleteNote(id: string) {
    return this.deleteOne('notes', id);
  }

  // ---------- events (table has no updated_at column) ----------

  public async getEvents(): Promise<Event[]> {
    const rows = await this.list<Event>('events', (q) => q.neq('status', 'cancelled'));
    return rows.sort((a, b) => byDateAsc(a.starts_at, b.starts_at));
  }

  public createEvent(item: Omit<Event, 'id' | 'created_at'>) {
    return this.insertOne<Event>('events', item);
  }

  public updateEvent(id: string, updates: Partial<Event>) {
    return this.updateOne<Event>('events', id, updates, false);
  }

  public async cancelEvent(id: string) {
    await this.updateEvent(id, { status: 'cancelled' });
  }

  public deleteEvent(id: string) {
    return this.deleteOne('events', id);
  }

  // ---------- resources ----------

  public async getResources(includeArchived = false): Promise<Resource[]> {
    const rows = await this.list<Resource>('resources', (q) =>
      includeArchived ? q : q.neq('status', 'archived'),
    );
    return rows.sort((a, b) => byDateDesc(a.created_at, b.created_at));
  }

  public createResource(item: Omit<Resource, 'id' | 'created_at' | 'updated_at'>) {
    return this.insertOne<Resource>('resources', item);
  }

  public updateResource(id: string, updates: Partial<Resource>) {
    return this.updateOne<Resource>('resources', id, updates, true);
  }

  public async archiveResource(id: string) {
    await this.updateResource(id, { status: 'archived' });
  }

  public deleteResource(id: string) {
    return this.deleteOne('resources', id);
  }

  // ---------- members (RLS: admins and the member themself only) ----------

  public async getMembers(): Promise<Member[]> {
    return this.list<Member>('members');
  }

  public createMember(item: Omit<Member, 'id' | 'created_at'>) {
    return this.insertOne<Member>('members', item);
  }

  public updateMember(id: string, updates: Partial<Member>) {
    return this.updateOne<Member>('members', id, updates, false);
  }

  // ---------- batch import ----------

  public async importBatch(
    items: ImportItem[],
    sectionId: string,
    createdBy = 'Section Administrator',
  ): Promise<{ insertedCount: number; entitiesByType: Record<EntityType, number> }> {
    const counts: Record<EntityType, number> = {
      announcement: 0,
      assignment: 0,
      task: 0,
      note: 0,
      event: 0,
      resource: 0,
    };
    const rowsByType: Record<EntityType, object[]> = {
      announcement: [],
      assignment: [],
      task: [],
      note: [],
      event: [],
      resource: [],
    };

    for (const item of items) {
      const { type, entity } = transformImportItemToEntity(item, sectionId, createdBy);
      // Postgres generates id / created_at / updated_at.
      const { id: _id, created_at: _c, updated_at: _u, ...row } = entity as unknown as Record<string, unknown>;
      rowsByType[type].push(row);
    }

    const done: string[] = [];
    let insertedCount = 0;

    for (const type of Object.keys(rowsByType) as EntityType[]) {
      const rows = rowsByType[type];
      if (rows.length === 0) continue;

      const { error } = await supabase.from(TABLE_BY_TYPE[type]).insert(rows);
      if (error) {
        const saved = done.length ? ` Already saved before the error: ${done.join(', ')}.` : '';
        throw new Error(`Import failed on ${TABLE_BY_TYPE[type]}: ${error.message}.${saved}`);
      }

      counts[type] = rows.length;
      insertedCount += rows.length;
      done.push(`${rows.length} ${TABLE_BY_TYPE[type]}`);
    }

    this.notify();
    return { insertedCount, entitiesByType: counts };
  }
}

export const databaseRepository: SectionRepository = new SupabaseSectionStore();
